# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d5bb407d6cf4494d01554c39e112bdac64861579608d058e19975837e92e153fe61ec3a61f6a24a82cdd53001eb34f3e1f1fc78b19ae63c2920af89d60d343a7

test:
  secret_key_base: 937b89214e5f587b7b77093aa528cfb788df5f072e910d55c555bbf20b736a52dab1a7c6f688a94137d8d1a7d82b7e0505333fe7ccfd560ca27f24dc974f67d8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
